on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: self-hosted
    outputs:
      pr: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node
          # The short ref name of the branch or tag that triggered
          # the workflow run. For example, `main` or `1.x`
          # target-branch: ${{ github.ref_name }}
          skip-github-release: true

      - name: print release_created
        run: echo "${{steps.release.outputs.release_created}}"

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org/

      - name: Restore Cache
        if: ${{ steps.release.outputs.release_created }}
        id: dependencies-cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-

      - name: Install Dependencies ğŸ”§
        if: ${{ steps.dependencies-cache.outputs.cache-hit != 'true' && steps.release.outputs.release_created }}
        run: |
          pnpm install

      - name: Build â˜•ï¸
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pnpm build:actions

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pnpm publish:actions
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  create-pr:
    runs-on: self-hosted
    needs: release-please
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: print pr
        run: echo "${{needs.release-please.outputs.pr}}"

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Merge develop into master"
          body: "This PR merges the latest changes from develop into master."
          base: master  # ç›®æ ‡åˆ†æ”¯
          branch: develop-to-master  # ä¸´æ—¶åˆ†æ”¯
          delete-branch: true  # åˆå¹¶ååˆ é™¤ä¸´æ—¶åˆ†æ”¯